### ISSUE TITLE
Need help on MVR/YAK/LNK/DEL/Move to trash

### ISSUE THREAD

**Issue by huijunchen9260** [huijunchen9260/dmenufm#15]
I try to simplify the code and realize that MVR, YAK, LNK, DEL, and move to trash function cannot handle filename with space.

Could anyone help me with this?

Thank you!

**Comment by huijunchen9260** [comment]
Also, I wish to simplify each menu and extract some independent function

**Comment by VebbNix** [comment]
In #16 I have made it so that bulk commands handle space properly. I do not seem to have the issue with single files though. If my PR doesn't work for you could you give a detailed example of a file name and exact process you are trying that doesn't work? I tried MVR on a file called "new file" and it seemed to work properly.

**Comment by huijunchen9260** [comment]
Fixed by VebbNix.
