### ISSUE TITLE
EYE Closes the active window

### ISSUE THREAD

**Issue by VebbNix** [huijunchen9260/dmenufm#31]
#19 
Hi,
Using 'EYE' closes whatever window I have open, for example, if I run dmenufm from a terminal, using EYE will cause the terminal to close, and thus end dmenufm.

Can I get an explanation of how EYE is supposed to differ from just normally opening the file with dmenufm so I could possibly assist in getting the outcome desired?

If it helps, I am on bspwm and installed dmenufm using the Makefile so I am using it as intended and it still gives this result. Also worth mentioning I do have wmctrl installed.

**Comment by huijunchen9260** [comment]
That's because somehow I just cannot figure out how to stop wmctrl from closing the windows that already opened. When I test it, somehow I cannot perfectly sure whether it close the opened window or not.

If you start dmenufm not from opening a terminal, like open in dmenu_run, then since no terminal opened, dmenufm will not close by `EYE` function. However, it is still not ideal for me.

**Comment by huijunchen9260** [comment]
@VebbNix can you look into the `FM_EYE` code in `dmenufm-action` and try to find it out for me? I've thought of it for 2 months but still cannot find out why.

The function of it is to quickly open and close (so just preview) files in the system that allows user to find the files that they want but somehow forgot the file name quickly. (Yeah, that's me LOL)

**Comment by VebbNix** [comment]
Just to make sure I am not using a broken install or something, what is the current outcome for you when you use EYE?
For me:
1. Select EYE in Action Menu
2. Kills current window
3. That seems to be it, I don't see it do anything else after that.

**Comment by huijunchen9260** [comment]
Really? For me, I can at least choose some choose and open it by dmenufm.

[FM_EYE](https://imgur.com/a/f2awqqK)

**Comment by VebbNix** [comment]
Hmm alright. I’ll try to reinstall and see what is causing this specific issue for me, and see if I can reproduce this issue so it can get fixed!

**Comment by huijunchen9260** [comment]
Thanks! I am conjecturing that may because of everyone's computer prioritize stuff differently...? I still wish to fix this function so that it is more stable and logically functional, not just capturing those small time difference.

**Comment by VebbNix** [comment]
Yeah, I’ll see what I can come up with once I get it working, and I’ll also see if I can figure out why it didn’t work at all for me so we can fix that too.

**Comment by VebbNix** [comment]
Alright I have discovered the issue for me not being able to use EYE.
The dmenu package in the Void Linux repository does not support the `-h` flag for height, here is some of my output demonstrating this with a line directly from the script.
```
$ dmenu -f -fn Monospace-15 -i -sb '#005577' -h 40 -l 10 -p "test"
usage: dmenu [-bfiv] [-l lines] [-p prompt] [-fn font] [-m monitor]
             [-nb color] [-nf color] [-sb color] [-sf color] [-w windowid]
$ dmenu -f -fn Monospace-15 -i -sb '#005577' -l 10 -p "test" 
^C
$ 
```

Can you verify that the Arch Linux official repository supports this flag, or is this a feature of a fork?

**Comment by huijunchen9260** [comment]
![image](https://user-images.githubusercontent.com/54217138/74993118-08b13180-5418-11ea-930e-57a6b4a8c7d0.png)

Definitely has it. I don't do any manupulation to dmenu, just download it from repository.

Since you mention it, I went to the suckless dmenu page, and found out in the suckless version of dmenu, they really don't have the `-h` flag:

[dmenu.1](https://git.suckless.org/dmenu/file/dmenu.1.html)

I should stop using `-h` flag and change it to other stuff instead.
